/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package snake;

/**
 *
 * @author izaelb
 */
public class ScoreBoard extends javax.swing.JPanel implements ScoreInterface{
    
    private int score;

    /**
     * Creates new form ScoreBoard
     */
    public ScoreBoard() {
        initComponents();
        score = 0;
    }
    
    @Override
    public void reset() {
        score = 0;
        updateLabel();
    }

    @Override
    public void increment(int increment) {
        score += increment;
        updateLabel();
    }

    @Override
    public int getScore() {
        return score;
    }
    
    public void updateLabel() {
       scoreL.setText("" + score);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        scoreL = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        scoreL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        scoreL.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 117;
        gridBagConstraints.ipady = 36;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(120, 120, 130, 113);
        add(scoreL, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel scoreL;
    // End of variables declaration//GEN-END:variables
}
