/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package snake;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author izaelb
 */


public class Scoreboard extends javax.swing.JPanel {
    private int score;
    private String playerName;
    private JLabel scoreLabel;
    

    /**
     * Creates new form Scoreboard
     */
    public Scoreboard() {
        initComponents();
        
        this.score = 0;
        this.playerName = playerName;

        setPreferredSize(new Dimension(0, 30));
        setBackground(Color.DARK_GRAY);
        setLayout(new BorderLayout());

        scoreLabel = new JLabel("Score for " + playerName + ": 0", SwingConstants.CENTER);
        scoreLabel.setForeground(Color.WHITE);
        scoreLabel.setFont(new Font("Arial", Font.BOLD, 14));

        add(scoreLabel, BorderLayout.CENTER);
    }
    
    public void addPoints(int points) {
        score += points;
        updateLabel();
    }

    public void reset() {
        score = 0;
        updateLabel();
    }

    private void updateLabel() {
        scoreLabel.setText("Score for " + playerName + ": " + score);
    }

    public int getScore() {
        return score;
    }

    public void setPlayerName(String playerName) {
        this.playerName = playerName;
        updateLabel();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
